[package]
name = "monolith_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = { version = "0.4" }
anyhow = "1"
futures-util = "0.3"
futures = "0.3"
async-trait = "0.1"
hyper = { version = "0.14", features = ["full"] }
hyper-tungstenite = "0.9"
lazy_static = "1"
env_logger = "0.10"