// Monolith's first application compiler. Tooling and code generation are Flexscript.
import "host.flex";
global sc_source=0;
global sc_at=0;
global sc_token=0;
global sc_line=1;
fn sc_fail(message) {h_die(h_cat3("schema line ",h_int(sc_line),h_cat(": ",message)));return 0;}
fn sc_letter(c) {return (c>=65 && c<=90)||(c>=97 && c<=122)||c==95;}
fn sc_next() {
    let more=1;
    while more {
        let c=load8(sc_source+sc_at);
        if c==32 || c==9 || c==13 || c==10 {if c==10 {sc_line=sc_line+1;}sc_at=sc_at+1;}
        else if c==47 && load8(sc_source+sc_at+1)==47 {while load8(sc_source+sc_at) && load8(sc_source+sc_at)!=10 {sc_at=sc_at+1;}}
        else {more=0;}
    }
    let start=sc_at;let c=load8(sc_source+sc_at);
    if sc_letter(c) || (c>=48 && c<=57) {
        while sc_letter(load8(sc_source+sc_at)) || (load8(sc_source+sc_at)>=48 && load8(sc_source+sc_at)<=57) {sc_at=sc_at+1;}
    }else if c {sc_at=sc_at+1;}
    sc_token=h_slice(sc_source+start,sc_at-start);return sc_token;
}
fn sc_expect(s) {if !h_equal(sc_token,s) {sc_fail(h_cat3("expected '",s,"'"));}sc_next();return 0;}
fn sc_ident() {
    if !sc_letter(load8(sc_token)) {sc_fail("expected identifier");}
    let s=sc_token;sc_next();return s;
}
fn sc_literal(s) {
    let b=h_buffer();h_text(b,"\"");let i=0;
    while load8(s+i) {
        let c=load8(s+i);
        if c==34 {h_text(b,"\\\"");}else if c==92 {h_text(b,"\\\\");}
        else if c==10 {h_text(b,"\\n");}else if c==13 {h_text(b,"\\r");}else if c==9 {h_text(b,"\\t");}
        else {h_append(b,s+i,1);}i=i+1;
    }h_text(b,"\"");return h_data(b);
}
fn sc_fn(b,name,value) {h_text(b,h_cat3("fn ",name,"() { return "));h_text(b,sc_literal(value));h_text(b,"; }\n");return 0;}
fn sc_alias(a,b) {let x=h_take(144);let y=h_take(144);if syscall(4,a,x,0,0,0,0)<0 || syscall(4,b,y,0,0,0,0)<0 {return 0;}return load64(x)==load64(y) && load64(x+8)==load64(y+8);}
fn sc_compile(path) {
    sc_source=h_read(path);sc_at=0;sc_line=1;sc_next();sc_expect("model");let name=sc_ident();sc_expect("{");
    let ddl=h_buffer();h_text(ddl,h_cat3("CREATE TABLE \"",name,"\" ("));
    let columns=h_buffer();let values=h_buffer();let inserts=h_buffer();let updates=h_buffer();let seen=h_args(0,0,0,0,0,0);
    let count=0;let id=0;let parameters=0;
    while !h_equal(sc_token,"}") {
        if !h_len(sc_token) {sc_fail("unclosed model");}let field=sc_ident();let i=0;
        while i<h_count(seen) {if h_equal(field,h_at(seen,i)) {sc_fail("duplicate field");}i=i+1;}h_add(seen,field);
        if count {h_text(ddl,",");h_text(columns,",");}count=count+1;
        let quoted=h_cat3("\"",field,"\"");h_text(ddl,quoted);h_text(columns,quoted);let primary=0;
        if h_equal(sc_token,"Int") {sc_next();sc_expect("primary");sc_expect("auto");if id {sc_fail("only one primary key is supported");}id=field;primary=1;h_text(ddl," INTEGER PRIMARY KEY AUTOINCREMENT");}
        else if h_equal(sc_token,"Text") {
            sc_next();sc_expect("(");let limit=h_number(sc_token);if limit<1 || limit>65536 {sc_fail("text limit must be 1..65536");}sc_next();sc_expect(")");
            h_text(ddl,h_cat(" TEXT NOT NULL CHECK(length(trim(",quoted));h_text(ddl,h_cat3(")) BETWEEN 1 AND ",h_int(limit),")"));
        }else if h_equal(sc_token,"Bool") {
            sc_next();sc_expect("default");let value=0;
            if h_equal(sc_token,"true") {value=1;}else if !h_equal(sc_token,"false") {sc_fail("boolean default must be true or false");}sc_next();
            h_text(ddl,h_cat3(" INTEGER NOT NULL DEFAULT ",h_int(value),h_cat3(" CHECK(",quoted," IN (0,1))")));
        }else {sc_fail("supported types are Int primary auto, Text(N), Bool default true/false");}
        sc_expect(";");
        if !primary {
            if parameters {h_text(inserts,",");h_text(values,",");h_text(updates,",");}parameters=parameters+1;
            h_text(inserts,quoted);h_text(values,h_cat("?",h_int(parameters)));h_text(updates,h_cat3(quoted,"=?",h_int(parameters)));
        }
    }
    sc_expect("}");if h_len(sc_token) {sc_fail("one model per schema is supported in this version");}
    if !id || parameters==0 {sc_fail("model requires an automatic primary key and data fields");}h_text(ddl,")");
    let table=h_cat3("\"",name,"\"");let key=h_cat3("\"",id,"\"");let out=h_buffer();h_text(out,"// Generated by Monolith. Edit the schema source.\n");
    sc_fn(out,"app_schema_name",name);sc_fn(out,"app_schema_sql",h_data(ddl));
    sc_fn(out,"app_select_sql",h_cat3(h_cat3("SELECT ",h_data(columns)," FROM "),table,h_cat(" ORDER BY ",key)));
    sc_fn(out,"app_insert_sql",h_cat3(h_cat3("INSERT INTO ",table," ("),h_data(inserts),h_cat3(") VALUES (",h_data(values),")")));
    sc_fn(out,"app_update_sql",h_cat3(h_cat3("UPDATE ",table," SET "),h_data(updates),h_cat3(" WHERE ",key,h_cat("=?",h_int(parameters+1)))));
    sc_fn(out,"app_delete_sql",h_cat3("DELETE FROM ",table,h_cat3(" WHERE ",key,"=?1")));
    sc_fn(out,"app_find_sql",h_cat3(h_cat3("SELECT ",h_data(columns)," FROM "),table,h_cat3(" WHERE ",key,"=?1")));
    return h_data(out);
}
fn main(argc,argv) {
    h_environment(argc,argv);
    if argc<3 || !h_equal(load64(argv+8),"build") {h_print(2,"Usage: monolith build APP --schema SCHEMA --compiler FLEX -o OUTPUT\nRun from Monolith's flex/ directory.\n");return 1;}
    let app=h_real(load64(argv+16));let schema=0;let compiler=0;let output=0;let i=3;
    while i<argc {
        h_assert(i+1<argc,"missing option value");let option=load64(argv+i*8);let value=load64(argv+(i+1)*8);
        if h_equal(option,"--schema") {h_assert(!schema,"duplicate schema option");schema=value;}
        else if h_equal(option,"--compiler") {h_assert(!compiler,"duplicate compiler option");compiler=value;}
        else if h_equal(option,"-o") {h_assert(!output,"duplicate output option");output=value;}
        else {h_die(h_cat("unknown option: ",option));}i=i+2;
    }
    h_assert(schema && compiler && output,"schema, compiler and output are required");
    let generated=sc_compile(schema);compiler=h_real(compiler);output=h_absolute(output);
    h_assert(!h_equal(app,output) && !h_equal(h_real(schema),output) && !h_equal(compiler,output) && !sc_alias(app,output) && !sc_alias(schema,output) && !sc_alias(compiler,output),"output aliases an input");
    h_mkdir(h_dir(output));let code=h_buffer();h_text(code,h_cat3("import ",sc_literal(app),";\n"));h_text(code,generated);
    sc_fn(code,"app_client_js",h_read("src/client.js"));sc_fn(code,"app_style_css",h_read("src/style.css"));
    let entry=h_cat(output,".generated.flex");h_assert(!sc_alias(entry,app) && !sc_alias(entry,schema) && !sc_alias(entry,compiler),"generated output aliases an input");h_save(entry,h_data(code));
    let random=h_take(8);h_assert(syscall(318,random,8,0,0,0,0)==8,"temporary name failed");let temporary=h_cat(output,h_cat(".tmp-",h_hex(random,8)));
    h_compile(compiler,entry,temporary);h_assert(syscall(82,temporary,output,0,0,0,0)==0,"atomic output replacement failed");h_print(1,h_cat3("Built ",output,"\n"));return 0;
}
