[package]
name = "monolith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
monolith_core = { path = "../core" }
tokio = { version = "1", features = ["full"] }
simple_logger = "4"
log = "0.4"